### ISSUE TITLE
ModuleNotFoundError: No module named 'numba.typing'`

### ISSUE THREAD

**Issue by JosueGauthier** [jaantollander/CrowdDynamics#358]
Hi, 
I have the following error when I try to run one example of crowddynamics. 

`Traceback (most recent call last):
  File "test_simm.py", line 1, in <module>
    from crowddynamics.examples.simulations import Hallway
  File "/home/josue/_crowdsim/crowddynamics/crowddynamics/examples/simulations.py", line 9, in <module>
    from crowddynamics.simulation.logic import Reset, Integrator, Fluctuation, \
  File "/home/josue/_crowdsim/crowddynamics/crowddynamics/simulation/logic.py", line 11, in <module>
    from crowddynamics.core.evacuation import exit_detection
  File "/home/josue/_crowdsim/crowddynamics/crowddynamics/core/evacuation.py", line 4, in <module>
    from numba.typing.typeof import typeof
ModuleNotFoundError: No module named 'numba.typing'`

I'm on numba 0.53.1
And i tried to go on numba 0.47.0 but then I have this issue : 
`TypeError: create_target_machine() got an unexpected keyword argument 'jitdebug'`

I don't know what to do... :=)
Thanks !

**Comment by geehadq** [comment]
Hello Josue,
Hope you're doing okay
Please did you solve the issue because I've got the same error.
I'm in need of this program for a school project ASAP

**Comment by JosueGauthier** [comment]
Hi Jihad, 

I never solve the issue ans this repo seems to be dead, so I move on and tried others things. 
I don't know what's your project purpose but you can check this repo : https://github.com/JosueGauthier/Sim_Crowd
it's a very basics crowd simulation but it can be a good base in order to do something better.

Good luck man !

Josué

**Comment by geehadq** [comment]
Hi Josue,

Thank you man for replying,
Actually, I'm in need of this simulation because It offers various evacuation environments, and also, It lets you vary _parametres_ such as the size of pedestrians, the door width, the number of pedestrians...
In other words, my project seeks to validate the 'social force model', and then propose a simulation, in order to draw function curves while varying these very _parametres_.
At first glance, I saw that your repo : https://github.com/JosueGauthier/Sim_Crowd uses **Fast-marching** algorithm. Could you please send an implementation of this algo in Python if Possible ? (or whatever programming language, I just want this algo so as to calculate geodesic distances in a domain -room with an exit- that can be represented by a 2D matrix)

Warm Regards,

Jihad

**Comment by antonvs88** [comment]
Hey @JoujouGeek666 and @JosueGauthier,

I'm sorry for the late reply! Finished my doctoral research two years ago, after which neither I, or @jaantollander, have maintained this Python package.

To me your problems sound like dependency issues, because this worked a few years ago on Ubuntu 16:04.

I have two suggestions to get the package working:

- See the tutorial https://www.youtube.com/watch?v=IN63QLZBN2U&ab_channel=JaanTollanderdeBalsch
- You could try to create a Docker container from Ubuntu 16:04 base image, and run the simulations from within the container.

I'm sorry for not having time to help more on these matters!
